
module.exports = {
//This file is designed to test that the entries into the database works
//It also shows how the information should be passed into the database

nursery_data: nursery_data ={"NurseryName":"Xaviers School for the Gifted",
				"StreetAddress":"Studley Park Rd & Nolan Ave",
				"City":"Kew",
				"State":"Victoria",
				"MainPhone":"0384811100",
				"ContactPhone":"0394015426",
				"Email":"ecms@ecms.org.au",
				"NurseryPassword":"TwoSheds",
				"SiblingDiscount":"0",
				"active":"1",
				"CommercialRegistrationNumber":"13012989761",
				"EarlyChildhoodEducationCertification":"1",
				"EarlyLearningFrameworkCertification":"1",
				"AboriginalProgram":"0",
				"ChildcareReduction":"0",
				"SpecialNeeds":"1",
				"registrationDate":"2020-9-1",
				"Language": ["English","Spanish","French"],
				"Services": [3,6],
				"Opening_Hours":["Weekdays","Statutory Holidays","Weekdays After 7pm"],
				"Meals": [1],
				"Programs": ["Licensed Preschool","School Age: Grade 1 to Age 12"],
				"specialPrograms": [{"id":1,"max":10},{"id":2,"max":15}]
},

nursery_data05: nursery_data ={"NurseryName":"Derby Meadows Preschool",
				"StreetAddress":"17 Winchester Ave",
				"City":"Epping",
				"State":"Victoria",
				"MainPhone":"0384811100",
				"ContactPhone":"0394015426",
				"Email":"ecms@ecms.org.au",
				"NurseryPassword":"TwoSheds",
				"SiblingDiscount":"0",
				"CommercialRegistrationNumber":"13012989761",
				"EarlyChildhoodEducationCertification":"1",
				"EarlyLearningFrameworkCertification":"1",
				"AboriginalProgram":"0",
				"ChildcareReduction":"0",
				"SpecialNeeds":"0",
				"registrationDate":"2020-9-1",
				"Language": ["English","Spanish","French"],
				"Services": [3,6],
				"Opening_Hours":["Weekdays","Statutory Holidays","Weekdays After 7pm"],
				"Meals": [3,5,9,10,15,18,19],
				"Programs": ["Licensed Preschool","School Age: Grade 1 to Age 12"]
},

nursery_data01: nursery_data01 ={"NurseryName":"High Street Preschool",
				"StreetAddress":"770 High Street",
				"City":"Epping",
				"State":"Victoria",
				"MainPhone":"0384811100",
				"ContactPhone":"0394015426",
				"Email":"ecms@ecms.org.au",
				"NurseryPassword":"TwoSheds",
				"SiblingDiscount":"0",
				"CommercialRegistrationNumber":"13012989761",
				"EarlyChildhoodEducationCertification":"0",
				"EarlyLearningFrameworkCertification":"1",
				"AboriginalProgram":"1",
				"ChildcareReduction":"1",
				"SpecialNeeds":"0",
				"registrationDate":"2020-9-1",
				"Language": ["English","French"],
				"Services": [3,6],
				"Opening_Hours":["Weekdays","Weekdays After 7pm"],
				"Meals": [3,5,9,10,15,18,19],
				"Programs": ["Licensed Preschool","School Age: Grade 1 to Age 12"]
},

nursery_data02: nursery_data02 ={"NurseryName":"Kookaburra Kindergarten",
				"StreetAddress":"34 George St",
				"City":"Reservoir",
				"State":"Victoria",
				"MainPhone":"0384811100",
				"ContactPhone":"0394015426",
				"Email":"ecms@ecms.org.au",
				"active":"1",
				"NurseryPassword":"TwoSheds",
				"SiblingDiscount":"0",
				"CommercialRegistrationNumber":"13012989761",
				"EarlyChildhoodEducationCertification":"0",
				"EarlyLearningFrameworkCertification":"1",
				"AboriginalProgram":"0",
				"ChildcareReduction":"1",
				"SpecialNeeds":"1",
				"registrationDate":"2020-9-1",
				"Language": ["English","Spanish","French"],
				"Services": [3,6],
				"Opening_Hours":["Weekdays","Statutory Holidays","Weekdays After 7pm"],
				"Meals": [3,5,9,10,15,18,19],
				"Programs": ["Licensed Preschool","School Age: Grade 1 to Age 12"]
},

nursery_data03: nursery_data03 ={"NurseryName":"Brunswick Kindergarten",
				"StreetAddress":"61 Glenlyon Rd",
				"City":"Brunswick",
				"State":"Victoria",
				"MainPhone":"0384811100",
				"ContactPhone":"0394015426",
				"Email":"ecms@ecms.org.au",
				"NurseryPassword":"TwoSheds",
				"SiblingDiscount":"0",
				"CommercialRegistrationNumber":"13012989761",
				"EarlyChildhoodEducationCertification":"1",
				"EarlyLearningFrameworkCertification":"0",
				"AboriginalProgram":"1",
				"ChildcareReduction":"0",
				"SpecialNeeds":"1",
				"registrationDate":"2020-9-1",
				"Language": ["English"],
				"Services": [3,6],
				"Opening_Hours":["Weekdays","Statutory Holidays","Weekdays After 7pm"],
				"Meals": [3,5,9,10,15,18,19],
				"Programs": ["Licensed Preschool","School Age: Grade 1 to Age 12"]
},

nursery_data04: nursery_data04 ={"NurseryName":"Park Street Childcare and Kindergarten",
				"StreetAddress":"785 Park St",
				"City":"Brunswick",
				"State":"Victoria",
				"MainPhone":"0384811100",
				"ContactPhone":"0394015426",
				"Email":"ecms@ecms.org.au",
				"NurseryPassword":"TwoSheds",
				"SiblingDiscount":"0",
				"CommercialRegistrationNumber":"13012989761",
				"EarlyChildhoodEducationCertification":"1",
				"EarlyLearningFrameworkCertification":"1",
				"AboriginalProgram":"0",
				"ChildcareReduction":"1",
				"SpecialNeeds":"1",
				"registrationDate":"2020-9-1",
				"Language": ["English","Mandarin"],
				"Services": [3,6],
				"Opening_Hours":["Weekdays","Statutory Holidays","Weekdays After 7pm"],
				"Meals": [3,5,9,10,15,18,19],
				"Programs": ["Licensed Preschool","School Age: Grade 1 to Age 12"]
},

parent_data_01: parent_data_01 = {"FirstName":"Scott",
		"Surname":"Morrison",
		"PreferredName":"Scotty",
		"DoB":"1960-2-19",
		"PhoneNumber":"0255674251",
		"AlternatePhone":"0443442778",
		"password":"ScoMo",
		"Email":"email@email.net",
		"LastLogin":"2020-9-1",
		"active":"1",
		"StreetAddress":"1 Mianga Ave",
		"City":"Engadine",
		"State":"New South Wales",
		"Gender":"M",
		"registrationDate":"2020-8-30",
		"Status":"1",
		"Language":["English"]},

parent_data_02: parent_data_02 = {"FirstName":"Arthur",
		"Surname":"Jackson",
		"PreferredName":"Two Sheds",
		"DoB":"1971-8-20",
		"PhoneNumber":"0355674251",
		"AlternatePhone":"0443552668",
		"password":"Python",
		"Email":"email@email.com",
		"LastLogin":"2020-8-30",
		"active":"1",
		"StreetAddress":"1 Spring Street",
		"City":"Melbourne",
		"State":"Victoria",
		"Gender":"M",
		"registrationDate":"2020-8-30",
		"Status":"1",
		"Language":["English","French"]},

child_data: child_data = {"ParentID":1,
			"FirstName":"Ronald",
			"Surname":"Jackson",
			"DoB":"2016-4-21",
			"Gender":"M",
			"SpecialNeeds":0,
			"HasSibling":0,
			"Language":["English","French"]},

update_login_data: update_login_data = {"userId":"1",
					"lastLogin":"2020-7-1"},

}